require("plugins.plugins")

require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.nvim-web-devicons")
require("plugins.leap")
require("plugins.neotree")
require("plugins.gitsigns")
require("plugins.null-ls")
require("plugins.nvim-cmp")
require("plugins.lualine")
require("plugins.comment")
require("plugins.indentline")
require("plugins.surround")
require("plugins.persisted")
require("plugins.project")
require("plugins.incline")
require("plugins.aerial")
